title: Connor Veenstra # your name (or website title) here
logo: "/images/logo.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Connor Veenstra is a Calvin University graduate with a Bachelor of Arts in Film Production and Journalism.
  <br><br>
  He has published over 100 articles covering entertainment, film and current events for multiple media organizations.  He also has experience in TV journalism as a multimedia reporter, covering local events in the Upper Peninsula.  He has published original creative works in poetry and short story collections.
  <br><br>
  His passions include film critique, history research and photography.
  <br><br>
  If you're looking for a teammate to create unique and compelling stories, who is passionate and teachable then don't hesitate to contact him at connorveenstra@gmail.com
  <br><br>
  <a href="https://www.linkedin.com/in/connor-veenstra-0085ba126/">View My LinkedIn Profile</a>
  
theme: jekyll-theme-minimal
#google_analytics: UA-000000-0 # your Google Analytics tracking ID here
github:
  is_project_page: false
